import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/commonComponents/Navbar";
import Footer from "@/commonComponents/Footer";
import "./styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <Navbar />
        <div className="antialiased bg-gray-100">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
